apiVersion: v1
kind: Service
metadata:
  name: resumeyaml
  namespace: default
  labels:
    app: resumeyaml
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      name: http
  selector:
    app: resumeyaml
